# -*- coding: utf-8 -*-
"""TNR_Filter_YOLO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JISDszpvVPoxrx32oUmnzzcxg3NNrdmL
"""
import os
import ast
import subprocess

test_img_list = sorted(os.listdir('./IoT_Data'))

async def detectCatByYolo(input_path):
    cmd = f'python yolov5/detect.py --weights ./model/best.pt --img 416 --conf 0.5 --source {input_path} --project static/img --name yolov5 --save-txt --save-conf --exist-ok'
    output = subprocess.check_output(cmd, shell=True)
    output = output.decode('utf-8')
    result_arr = ast.literal_eval(output)

    if result_arr[0] and result_arr[1]:
      return 1, True
    else:
      return -1, False