# -*- coding: utf-8 -*-
"""TNR_Filter_YOLO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JISDszpvVPoxrx32oUmnzzcxg3NNrdmL
"""

from google.colab import drive

drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd drive/MyDrive/TNR_Filter_Model

!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TNR_Filter_Model/yolov5

!pip install -r requirements.txt

from glob import glob
from sklearn.model_selection import train_test_split
import yaml
from IPython.display import Image
import os

# Commented out IPython magic to ensure Python compatibility.
# %cd cat_data

# 이미지 리스트 전체 불러오기 - 확장자 설정 필요
img_list = glob('./images/*')
print(len(img_list))

# TTV 분리
train, valid = train_test_split(img_list, test_size = 0.2, random_state = 2000)
print(len(train), len(valid))

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TNR_Filter_Model/yolov5/cat_data

# 데이터셋 txt
with open("./train.txt", "w") as f:
  f.write("\n".join(train) + "\n")
with open("./valid.txt", "w") as f:
  f.write("\n".join(valid) + "\n")

with open("./tnr_data.yaml", "r") as f:
  data = yaml.safe_load(f)

print(data)

data["train"] = "/content/drive/MyDrive/TNR_Filter_Model/yolov5/cat_data/train.txt"
data["val"] = "/content/drive/MyDrive/TNR_Filter_Model/yolov5/cat_data/valid.txt"

with open("./tnr_data.yaml", "w") as f:
  yaml.dump(data, f)

print(data)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TNR_Filter_Model/yolov5

!python train.py --img 640 --epochs 30 --data ./cat_data/tnr_data.yaml --weights yolov5s.pt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TNR_Filter_Model/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir /content/drive/MyDrive/TNR_Filter_Model/yolov5/runs/train/exp8

!python detect.py --weights ./runs/train/exp8/weights/best.pt --img 640 --conf 0.5 --source ./testData

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TNR_Filter_Model/yolov5

test_img_list = sorted(os.listdir('./IoT_Data'))
print(len(test_img_list))

target = 0

for index, f in enumerate(test_img_list):
  filename, ext = os.path.splitext(f)
  if filename == '20230424093412':
    print(filename, index)
    target = index
    break

val_image_path = test_img_list[target]
!python ./detect.py --weights ./runs/train/exp8/weights/best.pt --img 416 --conf 0.5 --source "IoT_Data/{val_image_path}"

